INSERT INTO STUDENT  VALUES ('1', 'Pradeep','Kumar','1234');
INSERT INTO STUDENT  VALUES ('2','Sunil','Kumar','20001');
INSERT INTO STUDENT  VALUES ('3','Tenis','Pajaria','2211');
INSERT INTO STUDENT  VALUES ('4','Bjriul','Kapaidya','1111');

INSERT INTO COURSE_STUDENT  VALUES ('1','1');
INSERT INTO COURSE_STUDENT  VALUES ('1','2');
INSERT INTO COURSE_STUDENT  VALUES ('2','1');
INSERT INTO COURSE_STUDENT  VALUES ('3','1');
INSERT INTO COURSE_STUDENT  VALUES ('4','1');

INSERT INTO COURSE  VALUES ('1', 'ICE','100','1','Memory');
INSERT INTO COURSE  VALUES ('2', 'ICE','101','1','Data');

INSERT INTO DEPARTMENT  VALUES ('ICE','tree');
INSERT INTO DEPARTMENT  VALUES ('ECE','road');

INSERT INTO INSTRUCTOR  VALUES ('100', 'ICE','Moorthy','Deen','Kummar','111112');
INSERT INTO INSTRUCTOR  VALUES ('101','ICE','sporty','praveen','Kummar','22211');
